import { sql } from '../../lib/db.js';

function escapeIcsText(value) {
  return String(value || '')
    .replaceAll('\\', '\\\\')
    .replaceAll(';', '\\;')
    .replaceAll(',', '\\,')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '');
}

function formatIcsDate(dateValue) {
  return String(dateValue).replaceAll('-', '');
}

function formatIcsDateTime(date = new Date()) {
  return date
    .toISOString()
    .replaceAll('-', '')
    .replaceAll(':', '')
    .replace(/\.\d{3}Z$/, 'Z');
}

function stripIcsExtension(token) {
  return String(token || '').replace(/\.ics$/i, '');
}

function createCalendarFeed({ property, channelConnection, blocks }) {
  const now = formatIcsDateTime();

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//One Plus One Luxe Retreat//Channel Calendar//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeIcsText(property.name)} Availability`,
    `X-WR-CALDESC:${escapeIcsText(
      `Unavailable dates for ${property.name}. Feed for ${channelConnection.channel_name}.`,
    )}`,
  ];

  for (const block of blocks) {
    const summary = `Unavailable - ${property.name}`;
    const description = [
      `Source: ${block.source}`,
      block.reason ? `Reason: ${block.reason}` : null,
      'Generated by One Plus One Luxe Retreat booking system.',
    ]
      .filter(Boolean)
      .join('\\n');

    lines.push(
      'BEGIN:VEVENT',
      `UID:${block.id}@one-plus-one-luxe-retreat`,
      `DTSTAMP:${now}`,
      `DTSTART;VALUE=DATE:${formatIcsDate(block.start_date)}`,
      `DTEND;VALUE=DATE:${formatIcsDate(block.end_date)}`,
      `SUMMARY:${escapeIcsText(summary)}`,
      `DESCRIPTION:${escapeIcsText(description)}`,
      'TRANSP:OPAQUE',
      'STATUS:CONFIRMED',
      'END:VEVENT',
    );
  }

  lines.push('END:VCALENDAR');

  return `${lines.join('\r\n')}\r\n`;
}

export default async function handler(request, response) {
  if (request.method !== 'GET') {
    return response.status(405).send('Method not allowed');
  }

  try {
    const url = new URL(request.url, `http://${request.headers.host}`);
    const pathParts = url.pathname.split('/').filter(Boolean);
    const rawToken = pathParts[pathParts.length - 1];
    const token = stripIcsExtension(rawToken);

    if (!token) {
      return response.status(400).send('Missing calendar token');
    }

    const connections = await sql`
      SELECT
        cc.id,
        cc.property_id,
        cc.channel_name,
        cc.ical_export_token,
        p.name,
        p.slug,
        p.public_location,
        p.timezone
      FROM channel_connections cc
      JOIN properties p
        ON p.id = cc.property_id
      WHERE cc.ical_export_token = ${token}
        AND cc.is_active = TRUE
        AND p.is_active = TRUE
      LIMIT 1
    `;

    const connection = connections[0];

    if (!connection) {
      return response.status(404).send('Calendar feed not found');
    }

    const property = {
      id: connection.property_id,
      name: connection.name,
      slug: connection.slug,
      public_location: connection.public_location,
      timezone: connection.timezone,
    };

    const channelConnection = {
      id: connection.id,
      channel_name: connection.channel_name,
      ical_export_token: connection.ical_export_token,
    };

    /*
      Export rule:
      - For Airbnb feed, export everything except Airbnb-sourced blocks.
      - For Vrbo feed, export everything except Vrbo-sourced blocks.
      - For Booking.com feed, export everything except Booking.com-sourced blocks.
      - For direct feed, export all active blocks.

      This avoids echoing a platform's own imported bookings back to itself.
    */
    const excludedSource =
      channelConnection.channel_name === 'direct'
        ? null
        : channelConnection.channel_name;

    const blocks = await sql`
      SELECT
        id,
        source,
        start_date::text AS start_date,
        end_date::text AS end_date,
        reason
      FROM availability_blocks
      WHERE property_id = ${property.id}
        AND status = 'active'
        AND (${excludedSource}::text IS NULL OR source <> ${excludedSource})
      ORDER BY start_date ASC
    `;

    const feed = createCalendarFeed({
      property,
      channelConnection,
      blocks,
    });

    response.setHeader('Content-Type', 'text/calendar; charset=utf-8');
    response.setHeader(
      'Content-Disposition',
      `inline; filename="${property.slug}-${channelConnection.channel_name}.ics"`,
    );
    response.setHeader('Cache-Control', 'public, max-age=300');

    return response.status(200).send(feed);
  } catch (error) {
    return response.status(500).send(`Calendar feed error: ${error.message}`);
  }
}
